version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads  # 持久化存储上传文件
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-default-secret-key}
    restart: always